name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: checkout
        uses: actions/checkout@v2

      - name: start Redis
        uses: supercharge/redis-github-action@1.4.0

      - name: build and test
        run: |
          go get -v
          go test -timeout=60s -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" > $GITHUB_WORKSPACE/profile.cov
          go build -race
        env:
          TZ: "America/Chicago"
          ENABLE_REDIS_TESTS: "true"

      - name: install golangci-lint and goveralls
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.47.2
          go install github.com/mattn/goveralls@latest

      - name: run linters
        run: $GITHUB_WORKSPACE/golangci-lint run --out-format=github-actions

      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
