name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
        id: go

      - name: checkout
        uses: actions/checkout@v4

      - name: start Redis
        uses: supercharge/redis-github-action@1.8.0

      - name: build and test
        run: |
          go get -v
          go test -timeout=60s -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" > $GITHUB_WORKSPACE/profile.cov
          go build -race
        env:
          TZ: "America/Chicago"
          ENABLE_REDIS_TESTS: "true"

      - name: build and test for v2
        run: |
          go get -v
          go test -timeout=60s -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp
          # combine the coverage files
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" | grep -v "mode:" >> $GITHUB_WORKSPACE/profile.cov
          go build -race
        env:
          TZ: "America/Chicago"
          ENABLE_REDIS_TESTS: "true"
        working-directory: v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: golangci-lint for v2
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: v2

      - name: submit coverage
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
